// <auto-generated />
using System;
using APH.SiteHub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APH.SiteHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SiteHubDbContext))]
    [Migration("20261010080802_AdoptExistingPostgresSchema")]
    partial class AdoptExistingPostgresSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APH.SiteHub.Domain.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("account_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_account_id");

                    b.Property<bool>("IsLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_limit");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("SecretKeyEncrypted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("secret_key_encrypted");

                    b.HasKey("Id")
                        .HasName("accounts_pkey");

                    b.HasIndex("Provider", "ExternalAccountId")
                        .IsUnique()
                        .HasDatabaseName("accounts_provider_external_id_unique");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("APH.SiteHub.Domain.AdminCredential", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("admin_credentials_pkey");

                    b.ToTable("admin_credentials", (string)null);
                });

            modelBuilder.Entity("APH.SiteHub.Domain.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_key");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("tags_pkey");

                    b.HasIndex("NameKey")
                        .IsUnique()
                        .HasDatabaseName("tags_name_key_unique");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("APH.SiteHub.Domain.Website", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("website_id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SearchText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("search_text");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("websites_pkey");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("websites_created_id_idx");

                    b.ToTable("websites", (string)null);
                });

            modelBuilder.Entity("APH.SiteHub.Domain.WebsiteTag", b =>
                {
                    b.Property<string>("WebsiteId")
                        .HasColumnType("text")
                        .HasColumnName("website_id");

                    b.Property<string>("TagId")
                        .HasColumnType("text")
                        .HasColumnName("tag_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("WebsiteId", "TagId")
                        .HasName("website_tags_website_id_tag_id_pk");

                    b.HasIndex("TagId")
                        .HasDatabaseName("website_tags_tag_idx");

                    b.ToTable("website_tags", (string)null);
                });

            modelBuilder.Entity("APH.SiteHub.Domain.WebsiteTag", b =>
                {
                    b.HasOne("APH.SiteHub.Domain.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("website_tags_tag_id_tags_tag_id_fk");

                    b.HasOne("APH.SiteHub.Domain.Website", null)
                        .WithMany("Links")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("website_tags_website_id_websites_website_id_fk");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("APH.SiteHub.Domain.Website", b =>
                {
                    b.Navigation("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
